import test from 'node:test'
import assert from 'node:assert/strict'
import {githubAuth,AuthSession} from '../src/auth.mjs'
import {createApp} from '../src/app.mjs'
const origin='https://reader.test'
function namespace(){const objects=new Map();return {idFromName:n=>n,get(id){if(!objects.has(id)){const data=new Map();let queue=Promise.resolve();const state={storage:{get:async k=>data.get(k),put:async(k,v)=>data.set(k,structuredClone(v)),deleteAll:async()=>data.clear(),setAlarm:async()=>{},deleteAlarm:async()=>{}},blockConcurrencyWhile(fn){const p=queue.then(fn);queue=p.catch(()=>{});return p}};objects.set(id,new AuthSession(state))}return objects.get(id)}}}
function fixture(){let calls=[];const env={PUBLIC_ORIGIN:origin,GITHUB_CLIENT_ID:'client',GITHUB_CLIENT_SECRET:'private-client-secret',AUTH_LIMITER:{limit:async()=>({success:true})},AUTH_SESSIONS:namespace(),ASSETS:{fetch:async()=>new Response('public')}};const auth=githubAuth(async(url,opts)=>{calls.push({url,opts});if(url.endsWith('/access_token'))return Response.json({access_token:'github-token',token_type:'bearer'});return Response.json({id:123,login:'tester',name:'Test User'})});return {env,auth,calls}}
async function begin(f){const r=await f.auth.fetch(new Request(origin+'/auth/login'),f.env);return {r,url:new URL(r.headers.get('Location')),cookie:r.headers.get('Set-Cookie').split(';')[0]}}
function callback(b,state=b.url.searchParams.get('state')){return new Request(origin+'/auth/callback?code=fixture-code&state='+state,{headers:{Cookie:b.cookie}})}
test('GitHub login uses state, PKCE, exact callback and no repository scopes',async()=>{const f=fixture(),b=await begin(f);assert.equal(b.url.origin,'https://github.com');assert.equal(b.url.searchParams.get('scope'),'');assert.equal(b.url.searchParams.get('code_challenge_method'),'S256');assert.equal(b.url.searchParams.get('code_challenge').length,43);assert.equal(b.url.searchParams.get('redirect_uri'),origin+'/auth/callback');assert.match(b.r.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.ok(!b.cookie.includes('private-client-secret'))})
test('valid callback verifies GitHub identity and creates revocable website session',async()=>{const f=fixture(),b=await begin(f),r=await f.auth.fetch(callback(b),f.env);assert.equal(r.status,303);const cookie=r.headers.getSetCookie().find(x=>x.startsWith('__Host-reader_account=')).split(';')[0];assert.ok(!cookie.includes('github-token'));const session=await f.auth.session(new Request(origin,{headers:{Cookie:cookie}}),f.env);assert.deepEqual(session,{userId:'gh_123',name:'Test User',login:'tester'});assert.equal(f.calls.length,2);assert.ok(f.calls[0].opts.body.get('code_verifier'));const app=createApp(f.auth);const logout=await app.fetch(new Request(origin+'/auth/logout',{method:'POST',headers:{Origin:origin,Cookie:cookie}}),f.env);assert.equal(logout.status,303);assert.equal(await f.auth.session(new Request(origin,{headers:{Cookie:cookie}}),f.env),null)})
test('wrong state, missing flow cookie, replay and expired records never authenticate',async()=>{const f=fixture();let b=await begin(f);assert.equal((await f.auth.fetch(callback(b,'wrong'),f.env)).status,400);assert.equal(f.calls.length,0);assert.equal((await f.auth.fetch(callback(b),f.env)).status,400);b=await begin(f);await f.auth.fetch(callback(b),f.env);assert.equal((await f.auth.fetch(callback(b),f.env)).status,400);assert.equal((await f.auth.fetch(new Request(origin+'/auth/callback?code=x&state=x'),f.env)).status,400);const object=f.env.AUTH_SESSIONS.get('expired');assert.equal((await object.fetch(new Request('https://session.internal/store',{method:'POST',body:JSON.stringify({kind:'session',expiresAt:1,user:{}})}))).status,400)})
test('fabricated cookies and request identity headers do not grant access',async()=>{const f=fixture(),app=createApp(f.auth);const r=await app.fetch(new Request(origin+'/api/catalog?userId=gh_123',{headers:{Cookie:'__Host-reader_account='+'a'.repeat(43),'X-User-ID':'gh_123'}}),f.env);assert.equal(r.status,401)})
test('OAuth rate limiting and missing config fail closed',async()=>{const f=fixture();assert.equal((await f.auth.fetch(new Request(origin+'/auth/login'),{...f.env,GITHUB_CLIENT_SECRET:''})).status,503);assert.equal((await f.auth.fetch(new Request(origin+'/auth/login'),{...f.env,AUTH_LIMITER:{limit:async()=>({success:false})}})).status,429)})
test('concurrent reuse of one OAuth flow allows only one callback',async()=>{const f=fixture(),b=await begin(f);const results=await Promise.all([f.auth.fetch(callback(b),f.env),f.auth.fetch(callback(b),f.env)]);assert.deepEqual(results.map(r=>r.status).sort(),[303,400]);assert.equal(f.calls.length,2)})
test('provider failure or invalid GitHub id never issues an account cookie',async()=>{for(const profile of [{id:'123',login:'test'},{id:-1,login:'test'}]){const f=fixture();f.auth=githubAuth(async url=>url.endsWith('/access_token')?Response.json({access_token:'t',token_type:'bearer'}):Response.json(profile));const b=await begin(f),r=await f.auth.fetch(callback(b),f.env);assert.equal(r.status,502);assert.equal(r.headers.get('Set-Cookie'),null)}})
